name: apiverve_colornamefinder
description: Color Name Finder is a tool for finding the closest named color from a hex color value. It uses color distance algorithms to match hex codes to CSS/HTML named colors and provides similarity scores for accurate color identification.
version: 1.1.14
homepage: https://apiverve.com/marketplace/colornamefinder?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/colornamefinder-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
